# Generated by Django 3.1 on 2020-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200821_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
