# Generated by Django 3.1 on 2020-08-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
    ]
