# Generated by Django 3.1 on 2020-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200827_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.CharField(blank=True, default='...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/unnamed.png', null=True, upload_to='profile_pics'),
        ),
    ]
